$$$
CREATE TRIGGER "UAT_JBF2"."JDT1_insert_trigger" AFTER INSERT ON "UAT_JBF2"."JDT1" REFERENCING NEW ROW CROW FOR EACH ROW 
BEGIN DECLARE COMPANY_STATE CHAR(1);SELECT "CompanySta" INTO COMPANY_STATE FROM "UAT_JBF2"."CINF";IF :COMPANY_STATE = 'V' THEN INSERT INTO "UAT_JBF2"."JDT1_tracking" VALUES("UAT_JBF2".ETL_S.NEXTVAL, 'I', Current_TimeStamp, :crow."TransId",:crow."Line_ID"); END IF; END
$$$
$$$
CREATE TRIGGER "UAT_JBF2"."JDT1_update_trigger" AFTER UPDATE ON "UAT_JBF2"."JDT1" REFERENCING NEW ROW CROW FOR EACH ROW 
BEGIN DECLARE COMPANY_STATE CHAR(1);SELECT "CompanySta" INTO COMPANY_STATE FROM "UAT_JBF2"."CINF";IF :COMPANY_STATE = 'V' THEN INSERT INTO "UAT_JBF2"."JDT1_tracking" VALUES("UAT_JBF2".ETL_S.NEXTVAL, 'U', Current_TimeStamp, :crow."TransId",:crow."Line_ID"); END IF; END
$$$
$$$
CREATE TRIGGER "UAT_JBF2"."JDT1_delete_trigger" AFTER DELETE ON "UAT_JBF2"."JDT1" REFERENCING OLD ROW CROW FOR EACH ROW 
BEGIN DECLARE COMPANY_STATE CHAR(1);SELECT "CompanySta" INTO COMPANY_STATE FROM "UAT_JBF2"."CINF";IF :COMPANY_STATE = 'V' THEN INSERT INTO "UAT_JBF2"."JDT1_tracking" VALUES("UAT_JBF2".ETL_S.NEXTVAL, 'D', Current_TimeStamp, :crow."TransId",:crow."Line_ID"); END IF; END
$$$