$$$
CREATE TRIGGER "UAT_JBF2"."OINV_delete_trigger" AFTER DELETE ON "UAT_JBF2"."OINV" REFERENCING OLD ROW CROW FOR EACH ROW 
BEGIN DECLARE COMPANY_STATE CHAR(1);SELECT "CompanySta" INTO COMPANY_STATE FROM "UAT_JBF2"."CINF";IF :COMPANY_STATE = 'V' THEN INSERT INTO "UAT_JBF2"."OINV_tracking" VALUES("UAT_JBF2".ETL_S.NEXTVAL, 'D', Current_TimeStamp, :crow."DocEntry"); END IF; END
$$$
$$$
CREATE TRIGGER "UAT_JBF2"."OINV_insert_trigger" AFTER INSERT ON "UAT_JBF2"."OINV" REFERENCING NEW ROW CROW FOR EACH ROW 
BEGIN DECLARE COMPANY_STATE CHAR(1);SELECT "CompanySta" INTO COMPANY_STATE FROM "UAT_JBF2"."CINF";IF :COMPANY_STATE = 'V' THEN INSERT INTO "UAT_JBF2"."OINV_tracking" VALUES("UAT_JBF2".ETL_S.NEXTVAL, 'I', Current_TimeStamp, :crow."DocEntry"); END IF; END
$$$
$$$
CREATE TRIGGER "UAT_JBF2"."OINV_update_trigger" AFTER UPDATE ON "UAT_JBF2"."OINV" REFERENCING NEW ROW CROW FOR EACH ROW 
BEGIN DECLARE COMPANY_STATE CHAR(1);SELECT "CompanySta" INTO COMPANY_STATE FROM "UAT_JBF2"."CINF";IF :COMPANY_STATE = 'V' THEN INSERT INTO "UAT_JBF2"."OINV_tracking" VALUES("UAT_JBF2".ETL_S.NEXTVAL, 'U', Current_TimeStamp, :crow."DocEntry"); END IF; END
$$$